### ISSUE TITLE
Running code as part of presentation

### ISSUE THREAD

**Issue by emicklei** [mkboudreau/docker-present#2]
Hi,

It appears that running some Go code inside a presentation is not being executed or logged into the window.
Do I need to pass some flag to make that work or is there another reason for this behavior?

**Comment by mkboudreau** [comment]
There was a need to pass an env var for the routable external ip address in the older version; however, I just made a bunch of updates and it looks like there is option to use the public golang playground. I have enabled that by default. I updated the README to reflect this. I also tested it locally.
